GET http://localhost:3000/

###


POST http://localhost:3000/
Content-Type: application/json

{
    "password": "cemsari"
}

###

POST http://localhost:3000/signin
Content-Type: application/json

{
    "password": "cemsari"
}